# Generated by Django 5.2 on 2025-04-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToAudioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('style_parameter', models.CharField(max_length=100)),
                ('generated_audio', models.FileField(upload_to='generated/')),
                ('additional_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
