# Generated by Django 5.2 on 2025-04-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processor', '0002_texttoaudioresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessingResult',
        ),
    ]
