# Generated by Django 5.2 on 2025-04-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_processor", "0003_delete_processingresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texttoaudioresult",
            name="additional_text",
        ),
        migrations.RemoveField(
            model_name="texttoaudioresult",
            name="style_parameter",
        ),
        migrations.AddField(
            model_name="texttoaudioresult",
            name="audio_file_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_to_audio_results",
                to="audio_processor.audiofile",
            ),
            preserve_default=False,
        ),
    ]
