# Generated by Django 5.2 on 2025-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_processor", "0004_remove_texttoaudioresult_additional_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
