# Generated by Django 5.2 on 2025-04-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_processor", "0005_audiofile_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="name",
            field=models.TextField(default="audio"),
            preserve_default=False,
        ),
    ]
