# Generated by Django 5.2 on 2025-04-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_processor", "0006_audiofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="name",
            field=models.TextField(default=""),
        ),
    ]
